steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/veritas-claims-analytics/medical-worker:latest', '-f', 'Dockerfile.worker', '.']
images:
- 'gcr.io/veritas-claims-analytics/medical-worker:latest'
